### ISSUE TITLE
HTTP response 500

### ISSUE THREAD

**Issue by gplssm** [openego/oedialect#1]
When I run run_eDisGo.py, sometimes I get an HTTP 500 response from the OEP. Here is the traceback.

```
(eDisGo) guido@rli-nb-17:~/rli_local/eDisGo$ python3 ~/rli_local/eDisGo_data/release_with_DP_v0.4.0/run_eDisGo.py 
/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO:keyring.backend:Loading SecretService
INFO:keyring.backend:Loading kwallet
INFO:keyring.backend:Loading macOS
INFO:keyring.backend:Loading windows
INFO:keyring.backend:Loading Gnome
INFO:keyring.backend:Loading Google
INFO:keyring.backend:Loading Windows (alt)
INFO:keyring.backend:Loading file
INFO:keyring.backend:Loading keyczar
INFO:keyring.backend:Loading multi
INFO:keyring.backend:Loading pyfs
WARNING:root:Right now only solar and wind generators can be imported from the oedb.
Traceback (most recent call last):
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/oedialect/engine.py", line 185, in post
    json_response = ans.json()
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guido/rli_local/eDisGo_data/release_with_DP_v0.4.0/run_eDisGo.py", line 12, in <module>
    grid.import_generators('nep2035')
  File "/home/guido/rli_local/eDisGo/edisgo/grid/network.py", line 349, in import_generators
    data_source=data_source)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 999, in import_generators
    _import_genos_from_oedb(network=network)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 1859, in _import_genos_from_oedb
    types_condition)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 1104, in _import_res_generators
    index_col='id')
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/pandas/io/sql.py", line 332, in read_sql_query
    parse_dates=parse_dates, chunksize=chunksize)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/pandas/io/sql.py", line 1087, in read_query
    result = self.execute(*args)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/pandas/io/sql.py", line 978, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2074, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 782, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1186, in _do_get
    self._dec_overflow()
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1183, in _do_get
    return self._create_connection()
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/oedialect/dbapi.py", line 7, in connect
    return OEConnection(**kwargs)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/oedialect/engine.py", line 36, in __init__
    response = self.post('advanced/connection/open', {})['content']
  File "/home/guido/virtualenvs/eDisGo/lib/python3.6/site-packages/oedialect/engine.py", line 187, in post
    raise ConnectionException('Answer contains no JSON: ' + repr(ans))
oedialect.engine.ConnectionException: Answer contains no JSON: <Response [500]>

```

A few minutes before, data could obtained successfully...
Any ideas or suggestions?

[Here](https://cloud.rl-institut.de/index.php/s/uRCVsu2WuukyvQt) is the data I used

**Comment by MGlauer** [comment]
From what I see in the logs, I would conclude that this was caused by a connection timeout. This may be caused by a networking bug that also causes other known inconveniences on the server apart from the OEP...

**Comment by gplssm** [comment]
I see... So, we cannot do that much right now (I know you tried hard to remove this bug).

**Comment by gplssm** [comment]
Are there any updates? Did you try something regarding the response 500 issue? Is it worth to test it again?

**Comment by Ludee** [comment]
@MGlauer just told me he fixed most of the oedialect and will push it today or latest tomorrow.

**Comment by MGlauer** [comment]
This was not a dialect bug, but an API-one. Has been fixed in [fa907c1a](https://github.com/openego/oeplatform/commit/fa907c1a76aacb636c7cc5d3a89cc572b0c7a981)

**Comment by MGlauer** [comment]
This bug was not part of the fixes as this is not due to some bug on the platform side, but some unidentified fault outside the server.

**Comment by gplssm** [comment]
Thanks for clarifying again! I'll close this issue...
